// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gen_superpop_cpp
Rcpp::List gen_superpop_cpp(const arma::vec& mu_fixed, double sigmae2, double sigmau2, const arma::ivec& obs_dom, const arma::ivec& n_pop, int N_dom_pop, const std::string& transformation, double lambda, double shift);
RcppExport SEXP _emdi2_gen_superpop_cpp(SEXP mu_fixedSEXP, SEXP sigmae2SEXP, SEXP sigmau2SEXP, SEXP obs_domSEXP, SEXP n_popSEXP, SEXP N_dom_popSEXP, SEXP transformationSEXP, SEXP lambdaSEXP, SEXP shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_fixed(mu_fixedSEXP);
    Rcpp::traits::input_parameter< double >::type sigmae2(sigmae2SEXP);
    Rcpp::traits::input_parameter< double >::type sigmau2(sigmau2SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type obs_dom(obs_domSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_pop(n_popSEXP);
    Rcpp::traits::input_parameter< int >::type N_dom_pop(N_dom_popSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type transformation(transformationSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type shift(shiftSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_superpop_cpp(mu_fixed, sigmae2, sigmau2, obs_dom, n_pop, N_dom_pop, transformation, lambda, shift));
    return rcpp_result_gen;
END_RCPP
}
// gen_bootstrap_sample_cpp
arma::vec gen_bootstrap_sample_cpp(const arma::mat& X_smp, const arma::vec& betas, double sigmae2, double sigmau2, const arma::vec& vu_tmp, const Rcpp::IntegerVector& smp_to_pop_map, const arma::ivec& n_smp, const std::string& transformation, double lambda, double shift);
RcppExport SEXP _emdi2_gen_bootstrap_sample_cpp(SEXP X_smpSEXP, SEXP betasSEXP, SEXP sigmae2SEXP, SEXP sigmau2SEXP, SEXP vu_tmpSEXP, SEXP smp_to_pop_mapSEXP, SEXP n_smpSEXP, SEXP transformationSEXP, SEXP lambdaSEXP, SEXP shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_smp(X_smpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< double >::type sigmae2(sigmae2SEXP);
    Rcpp::traits::input_parameter< double >::type sigmau2(sigmau2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vu_tmp(vu_tmpSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type smp_to_pop_map(smp_to_pop_mapSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_smp(n_smpSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type transformation(transformationSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type shift(shiftSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_bootstrap_sample_cpp(X_smp, betas, sigmae2, sigmau2, vu_tmp, smp_to_pop_map, n_smp, transformation, lambda, shift));
    return rcpp_result_gen;
END_RCPP
}
// fh_bc_integral_cpp
arma::vec fh_bc_integral_cpp(const arma::vec& mu, const arma::vec& sigma);
RcppExport SEXP _emdi2_fh_bc_integral_cpp(SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_bc_integral_cpp(mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// fh_boot_arcsin_cpp
Rcpp::List fh_boot_arcsin_cpp(double sigmau2, const arma::vec& vardir, const arma::vec& beta, const arma::mat& X, const arma::mat& predX, const arma::ivec& is_in, const arma::mat& v_boot, const arma::mat& e_boot, const arma::vec& eblup_corr, bool bc, double lower, double upper, int threads);
RcppExport SEXP _emdi2_fh_boot_arcsin_cpp(SEXP sigmau2SEXP, SEXP vardirSEXP, SEXP betaSEXP, SEXP XSEXP, SEXP predXSEXP, SEXP is_inSEXP, SEXP v_bootSEXP, SEXP e_bootSEXP, SEXP eblup_corrSEXP, SEXP bcSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigmau2(sigmau2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vardir(vardirSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type predX(predXSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type is_in(is_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type v_boot(v_bootSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type e_boot(e_bootSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eblup_corr(eblup_corrSEXP);
    Rcpp::traits::input_parameter< bool >::type bc(bcSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_boot_arcsin_cpp(sigmau2, vardir, beta, X, predX, is_in, v_boot, e_boot, eblup_corr, bc, lower, upper, threads));
    return rcpp_result_gen;
END_RCPP
}
// fh_eblup_core_cpp
Rcpp::List fh_eblup_core_cpp(double sigmau2, const arma::vec& direct, const arma::mat& X, const arma::vec& vardir);
RcppExport SEXP _emdi2_fh_eblup_core_cpp(SEXP sigmau2SEXP, SEXP directSEXP, SEXP XSEXP, SEXP vardirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigmau2(sigmau2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type direct(directSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vardir(vardirSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_eblup_core_cpp(sigmau2, direct, X, vardir));
    return rcpp_result_gen;
END_RCPP
}
// fh_eblup_sfh_cpp
Rcpp::List fh_eblup_sfh_cpp(double sigmau2, double rho, const arma::vec& direct, const arma::mat& X, const arma::vec& vardir, const arma::mat& W);
RcppExport SEXP _emdi2_fh_eblup_sfh_cpp(SEXP sigmau2SEXP, SEXP rhoSEXP, SEXP directSEXP, SEXP XSEXP, SEXP vardirSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigmau2(sigmau2SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type direct(directSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vardir(vardirSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_eblup_sfh_cpp(sigmau2, rho, direct, X, vardir, W));
    return rcpp_result_gen;
END_RCPP
}
// fh_jackknife_cpp
Rcpp::List fh_jackknife_cpp(const arma::vec& direct, const arma::mat& X, const arma::vec& vardir, double sigmau2, const arma::vec& fh_full, double lower, double upper, double tol, int threads);
RcppExport SEXP _emdi2_fh_jackknife_cpp(SEXP directSEXP, SEXP XSEXP, SEXP vardirSEXP, SEXP sigmau2SEXP, SEXP fh_fullSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP tolSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type direct(directSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vardir(vardirSEXP);
    Rcpp::traits::input_parameter< double >::type sigmau2(sigmau2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fh_full(fh_fullSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_jackknife_cpp(direct, X, vardir, sigmau2, fh_full, lower, upper, tol, threads));
    return rcpp_result_gen;
END_RCPP
}
// fh_mse_pr_cpp
Rcpp::List fh_mse_pr_cpp(double sigmau2, const arma::mat& X, const arma::vec& vardir, const arma::mat& pred_X);
RcppExport SEXP _emdi2_fh_mse_pr_cpp(SEXP sigmau2SEXP, SEXP XSEXP, SEXP vardirSEXP, SEXP pred_XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigmau2(sigmau2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vardir(vardirSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pred_X(pred_XSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_mse_pr_cpp(sigmau2, X, vardir, pred_X));
    return rcpp_result_gen;
END_RCPP
}
// fh_mse_spatial_cpp
arma::vec fh_mse_spatial_cpp(double sigmau2, double rho, const arma::mat& X, const arma::vec& vardir, const arma::mat& W, const std::string& method);
RcppExport SEXP _emdi2_fh_mse_spatial_cpp(SEXP sigmau2SEXP, SEXP rhoSEXP, SEXP XSEXP, SEXP vardirSEXP, SEXP WSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigmau2(sigmau2SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vardir(vardirSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_mse_spatial_cpp(sigmau2, rho, X, vardir, W, method));
    return rcpp_result_gen;
END_RCPP
}
// fh_reml_loglik_cpp
double fh_reml_loglik_cpp(double sigmau2, const arma::vec& direct, const arma::mat& X, const arma::vec& vardir);
RcppExport SEXP _emdi2_fh_reml_loglik_cpp(SEXP sigmau2SEXP, SEXP directSEXP, SEXP XSEXP, SEXP vardirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigmau2(sigmau2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type direct(directSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vardir(vardirSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_reml_loglik_cpp(sigmau2, direct, X, vardir));
    return rcpp_result_gen;
END_RCPP
}
// fh_estsigmau2_reml_cpp
double fh_estsigmau2_reml_cpp(const arma::vec& direct, const arma::mat& X, const arma::vec& vardir, double lower, double upper, double tol);
RcppExport SEXP _emdi2_fh_estsigmau2_reml_cpp(SEXP directSEXP, SEXP XSEXP, SEXP vardirSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type direct(directSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vardir(vardirSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_estsigmau2_reml_cpp(direct, X, vardir, lower, upper, tol));
    return rcpp_result_gen;
END_RCPP
}
// fh_sreml_cpp
Rcpp::List fh_sreml_cpp(const arma::vec& direct, const arma::mat& X, const arma::vec& vardir, const arma::mat& W, int maxit, double tol);
RcppExport SEXP _emdi2_fh_sreml_cpp(SEXP directSEXP, SEXP XSEXP, SEXP vardirSEXP, SEXP WSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type direct(directSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vardir(vardirSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fh_sreml_cpp(direct, X, vardir, W, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// compute_domain_indicators_cpp
arma::vec compute_domain_indicators_cpp(const arma::vec& y, const arma::vec& weights, double threshold);
RcppExport SEXP _emdi2_compute_domain_indicators_cpp(SEXP ySEXP, SEXP weightsSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_domain_indicators_cpp(y, weights, threshold));
    return rcpp_result_gen;
END_RCPP
}
// compute_domain_indicators_selective_cpp
arma::vec compute_domain_indicators_selective_cpp(const arma::vec& y, const arma::vec& weights, double threshold, int indicator_mask);
RcppExport SEXP _emdi2_compute_domain_indicators_selective_cpp(SEXP ySEXP, SEXP weightsSEXP, SEXP thresholdSEXP, SEXP indicator_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type indicator_mask(indicator_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_domain_indicators_selective_cpp(y, weights, threshold, indicator_mask));
    return rcpp_result_gen;
END_RCPP
}
// compute_all_indicators_cpp
arma::mat compute_all_indicators_cpp(const arma::vec& y, const arma::vec& weights, const arma::ivec& domain_ids, double threshold, int n_domains);
RcppExport SEXP _emdi2_compute_all_indicators_cpp(SEXP ySEXP, SEXP weightsSEXP, SEXP domain_idsSEXP, SEXP thresholdSEXP, SEXP n_domainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type domain_ids(domain_idsSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type n_domains(n_domainsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_all_indicators_cpp(y, weights, domain_ids, threshold, n_domains));
    return rcpp_result_gen;
END_RCPP
}
// data_transform_cpp
Rcpp::List data_transform_cpp(const arma::vec& y_raw, const std::string& transformation, double lambda);
RcppExport SEXP _emdi2_data_transform_cpp(SEXP y_rawSEXP, SEXP transformationSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_raw(y_rawSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type transformation(transformationSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(data_transform_cpp(y_raw, transformation, lambda));
    return rcpp_result_gen;
END_RCPP
}
// lme_fit_cpp
Rcpp::List lme_fit_cpp(const arma::vec& y_transformed, const arma::mat& X, const arma::ivec& n_d);
RcppExport SEXP _emdi2_lme_fit_cpp(SEXP y_transformedSEXP, SEXP XSEXP, SEXP n_dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_transformed(y_transformedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_d(n_dSEXP);
    rcpp_result_gen = Rcpp::wrap(lme_fit_cpp(y_transformed, X, n_d));
    return rcpp_result_gen;
END_RCPP
}
// model_par_weighted_cpp
Rcpp::List model_par_weighted_cpp(const arma::vec& y_transformed, const arma::mat& X, const arma::vec& weights, const arma::ivec& n_d, double sigma2_e, double sigma2_u);
RcppExport SEXP _emdi2_model_par_weighted_cpp(SEXP y_transformedSEXP, SEXP XSEXP, SEXP weightsSEXP, SEXP n_dSEXP, SEXP sigma2_eSEXP, SEXP sigma2_uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_transformed(y_transformedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_d(n_dSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_e(sigma2_eSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_u(sigma2_uSEXP);
    rcpp_result_gen = Rcpp::wrap(model_par_weighted_cpp(y_transformed, X, weights, n_d, sigma2_e, sigma2_u));
    return rcpp_result_gen;
END_RCPP
}
// set_omp_threads
int set_omp_threads(int n);
RcppExport SEXP _emdi2_set_omp_threads(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(set_omp_threads(n));
    return rcpp_result_gen;
END_RCPP
}
// get_omp_threads
int get_omp_threads();
RcppExport SEXP _emdi2_get_omp_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_omp_threads());
    return rcpp_result_gen;
END_RCPP
}
// monte_carlo_cpp
Rcpp::List monte_carlo_cpp(const arma::vec& mu, double sigmae2, double sigmau2, const arma::vec& sigmav2, const arma::ivec& domain_ids, const arma::ivec& obs_dom, const arma::ivec& dist_obs_dom, const arma::ivec& n_pop, int N_dom_pop, int N_dom_smp, int N_dom_unobs, int L, double threshold, const std::string& transformation, double lambda, double shift, const arma::vec& pop_weights, int n_indicators, Rcpp::Nullable<Rcpp::IntegerVector> agg_domain_ids, int N_dom_agg, int indicator_mask, int threads);
RcppExport SEXP _emdi2_monte_carlo_cpp(SEXP muSEXP, SEXP sigmae2SEXP, SEXP sigmau2SEXP, SEXP sigmav2SEXP, SEXP domain_idsSEXP, SEXP obs_domSEXP, SEXP dist_obs_domSEXP, SEXP n_popSEXP, SEXP N_dom_popSEXP, SEXP N_dom_smpSEXP, SEXP N_dom_unobsSEXP, SEXP LSEXP, SEXP thresholdSEXP, SEXP transformationSEXP, SEXP lambdaSEXP, SEXP shiftSEXP, SEXP pop_weightsSEXP, SEXP n_indicatorsSEXP, SEXP agg_domain_idsSEXP, SEXP N_dom_aggSEXP, SEXP indicator_maskSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigmae2(sigmae2SEXP);
    Rcpp::traits::input_parameter< double >::type sigmau2(sigmau2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigmav2(sigmav2SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type domain_ids(domain_idsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type obs_dom(obs_domSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dist_obs_dom(dist_obs_domSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_pop(n_popSEXP);
    Rcpp::traits::input_parameter< int >::type N_dom_pop(N_dom_popSEXP);
    Rcpp::traits::input_parameter< int >::type N_dom_smp(N_dom_smpSEXP);
    Rcpp::traits::input_parameter< int >::type N_dom_unobs(N_dom_unobsSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type transformation(transformationSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type shift(shiftSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pop_weights(pop_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type n_indicators(n_indicatorsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type agg_domain_ids(agg_domain_idsSEXP);
    Rcpp::traits::input_parameter< int >::type N_dom_agg(N_dom_aggSEXP);
    Rcpp::traits::input_parameter< int >::type indicator_mask(indicator_maskSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(monte_carlo_cpp(mu, sigmae2, sigmau2, sigmav2, domain_ids, obs_dom, dist_obs_dom, n_pop, N_dom_pop, N_dom_smp, N_dom_unobs, L, threshold, transformation, lambda, shift, pop_weights, n_indicators, agg_domain_ids, N_dom_agg, indicator_mask, threads));
    return rcpp_result_gen;
END_RCPP
}
// parametric_bootstrap_cpp
arma::mat parametric_bootstrap_cpp(const arma::mat& X_pop, const arma::vec& mu_fixed_orig, const arma::ivec& n_pop, const arma::ivec& obs_dom, const arma::ivec& dist_obs_dom, const arma::vec& pop_weights, int N_pop, int N_dom_pop, const arma::mat& X_smp, const arma::ivec& n_smp, const arma::ivec& smp_domain_ids, const arma::ivec& smp_to_pop_map, int N_smp, int N_dom_smp, const arma::vec& betas_orig, double sigmae2_orig, double sigmau2_orig, int N_dom_smp_selected, int N_dom_unobs, int B, int L, double threshold, const std::string& transformation, double lambda_orig, double shift_orig, double interval_lower, double interval_upper, Rcpp::Nullable<Rcpp::IntegerVector> agg_domain_ids_pop, int N_dom_agg, Rcpp::Nullable<Rcpp::NumericVector> smp_weights, int indicator_mask, int threads);
RcppExport SEXP _emdi2_parametric_bootstrap_cpp(SEXP X_popSEXP, SEXP mu_fixed_origSEXP, SEXP n_popSEXP, SEXP obs_domSEXP, SEXP dist_obs_domSEXP, SEXP pop_weightsSEXP, SEXP N_popSEXP, SEXP N_dom_popSEXP, SEXP X_smpSEXP, SEXP n_smpSEXP, SEXP smp_domain_idsSEXP, SEXP smp_to_pop_mapSEXP, SEXP N_smpSEXP, SEXP N_dom_smpSEXP, SEXP betas_origSEXP, SEXP sigmae2_origSEXP, SEXP sigmau2_origSEXP, SEXP N_dom_smp_selectedSEXP, SEXP N_dom_unobsSEXP, SEXP BSEXP, SEXP LSEXP, SEXP thresholdSEXP, SEXP transformationSEXP, SEXP lambda_origSEXP, SEXP shift_origSEXP, SEXP interval_lowerSEXP, SEXP interval_upperSEXP, SEXP agg_domain_ids_popSEXP, SEXP N_dom_aggSEXP, SEXP smp_weightsSEXP, SEXP indicator_maskSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_pop(X_popSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_fixed_orig(mu_fixed_origSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_pop(n_popSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type obs_dom(obs_domSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dist_obs_dom(dist_obs_domSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pop_weights(pop_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type N_pop(N_popSEXP);
    Rcpp::traits::input_parameter< int >::type N_dom_pop(N_dom_popSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_smp(X_smpSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_smp(n_smpSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type smp_domain_ids(smp_domain_idsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type smp_to_pop_map(smp_to_pop_mapSEXP);
    Rcpp::traits::input_parameter< int >::type N_smp(N_smpSEXP);
    Rcpp::traits::input_parameter< int >::type N_dom_smp(N_dom_smpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type betas_orig(betas_origSEXP);
    Rcpp::traits::input_parameter< double >::type sigmae2_orig(sigmae2_origSEXP);
    Rcpp::traits::input_parameter< double >::type sigmau2_orig(sigmau2_origSEXP);
    Rcpp::traits::input_parameter< int >::type N_dom_smp_selected(N_dom_smp_selectedSEXP);
    Rcpp::traits::input_parameter< int >::type N_dom_unobs(N_dom_unobsSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type transformation(transformationSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_orig(lambda_origSEXP);
    Rcpp::traits::input_parameter< double >::type shift_orig(shift_origSEXP);
    Rcpp::traits::input_parameter< double >::type interval_lower(interval_lowerSEXP);
    Rcpp::traits::input_parameter< double >::type interval_upper(interval_upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type agg_domain_ids_pop(agg_domain_ids_popSEXP);
    Rcpp::traits::input_parameter< int >::type N_dom_agg(N_dom_aggSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type smp_weights(smp_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type indicator_mask(indicator_maskSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parametric_bootstrap_cpp(X_pop, mu_fixed_orig, n_pop, obs_dom, dist_obs_dom, pop_weights, N_pop, N_dom_pop, X_smp, n_smp, smp_domain_ids, smp_to_pop_map, N_smp, N_dom_smp, betas_orig, sigmae2_orig, sigmau2_orig, N_dom_smp_selected, N_dom_unobs, B, L, threshold, transformation, lambda_orig, shift_orig, interval_lower, interval_upper, agg_domain_ids_pop, N_dom_agg, smp_weights, indicator_mask, threads));
    return rcpp_result_gen;
END_RCPP
}
// fmt_duration_cpp
std::string fmt_duration_cpp(double secs);
RcppExport SEXP _emdi2_fmt_duration_cpp(SEXP secsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type secs(secsSEXP);
    rcpp_result_gen = Rcpp::wrap(fmt_duration_cpp(secs));
    return rcpp_result_gen;
END_RCPP
}
// progress_line_cpp
std::string progress_line_cpp(int i, int total, double elapsed, double start_epoch, std::string label);
RcppExport SEXP _emdi2_progress_line_cpp(SEXP iSEXP, SEXP totalSEXP, SEXP elapsedSEXP, SEXP start_epochSEXP, SEXP labelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type total(totalSEXP);
    Rcpp::traits::input_parameter< double >::type elapsed(elapsedSEXP);
    Rcpp::traits::input_parameter< double >::type start_epoch(start_epochSEXP);
    Rcpp::traits::input_parameter< std::string >::type label(labelSEXP);
    rcpp_result_gen = Rcpp::wrap(progress_line_cpp(i, total, elapsed, start_epoch, label));
    return rcpp_result_gen;
END_RCPP
}
// progress_header_cpp
std::string progress_header_cpp(std::string title, int total, std::string label, double start_epoch);
RcppExport SEXP _emdi2_progress_header_cpp(SEXP titleSEXP, SEXP totalSEXP, SEXP labelSEXP, SEXP start_epochSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type title(titleSEXP);
    Rcpp::traits::input_parameter< int >::type total(totalSEXP);
    Rcpp::traits::input_parameter< std::string >::type label(labelSEXP);
    Rcpp::traits::input_parameter< double >::type start_epoch(start_epochSEXP);
    rcpp_result_gen = Rcpp::wrap(progress_header_cpp(title, total, label, start_epoch));
    return rcpp_result_gen;
END_RCPP
}
// std_transform_y_cpp
arma::vec std_transform_y_cpp(const arma::vec& y_raw, const std::string& transformation, double lambda);
RcppExport SEXP _emdi2_std_transform_y_cpp(SEXP y_rawSEXP, SEXP transformationSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_raw(y_rawSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type transformation(transformationSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(std_transform_y_cpp(y_raw, transformation, lambda));
    return rcpp_result_gen;
END_RCPP
}
// reml_loglik_cpp
double reml_loglik_cpp(double lambda, const arma::vec& y_raw, const arma::mat& X, const arma::ivec& domain_ids, const arma::ivec& n_d, const std::string& transformation);
RcppExport SEXP _emdi2_reml_loglik_cpp(SEXP lambdaSEXP, SEXP y_rawSEXP, SEXP XSEXP, SEXP domain_idsSEXP, SEXP n_dSEXP, SEXP transformationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_raw(y_rawSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type domain_ids(domain_idsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_d(n_dSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type transformation(transformationSEXP);
    rcpp_result_gen = Rcpp::wrap(reml_loglik_cpp(lambda, y_raw, X, domain_ids, n_d, transformation));
    return rcpp_result_gen;
END_RCPP
}
// optimal_parameter_cpp
double optimal_parameter_cpp(const arma::vec& y, const arma::mat& X, const arma::ivec& domain_ids, const arma::ivec& n_d, const std::string& transformation, double lower, double upper);
RcppExport SEXP _emdi2_optimal_parameter_cpp(SEXP ySEXP, SEXP XSEXP, SEXP domain_idsSEXP, SEXP n_dSEXP, SEXP transformationSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type domain_ids(domain_idsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_d(n_dSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type transformation(transformationSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(optimal_parameter_cpp(y, X, domain_ids, n_d, transformation, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// back_transform_cpp
Rcpp::NumericVector back_transform_cpp(const arma::vec& y, const std::string& transformation, double lambda, double shift);
RcppExport SEXP _emdi2_back_transform_cpp(SEXP ySEXP, SEXP transformationSEXP, SEXP lambdaSEXP, SEXP shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type transformation(transformationSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type shift(shiftSEXP);
    rcpp_result_gen = Rcpp::wrap(back_transform_cpp(y, transformation, lambda, shift));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_emdi2_gen_superpop_cpp", (DL_FUNC) &_emdi2_gen_superpop_cpp, 9},
    {"_emdi2_gen_bootstrap_sample_cpp", (DL_FUNC) &_emdi2_gen_bootstrap_sample_cpp, 10},
    {"_emdi2_fh_bc_integral_cpp", (DL_FUNC) &_emdi2_fh_bc_integral_cpp, 2},
    {"_emdi2_fh_boot_arcsin_cpp", (DL_FUNC) &_emdi2_fh_boot_arcsin_cpp, 13},
    {"_emdi2_fh_eblup_core_cpp", (DL_FUNC) &_emdi2_fh_eblup_core_cpp, 4},
    {"_emdi2_fh_eblup_sfh_cpp", (DL_FUNC) &_emdi2_fh_eblup_sfh_cpp, 6},
    {"_emdi2_fh_jackknife_cpp", (DL_FUNC) &_emdi2_fh_jackknife_cpp, 9},
    {"_emdi2_fh_mse_pr_cpp", (DL_FUNC) &_emdi2_fh_mse_pr_cpp, 4},
    {"_emdi2_fh_mse_spatial_cpp", (DL_FUNC) &_emdi2_fh_mse_spatial_cpp, 6},
    {"_emdi2_fh_reml_loglik_cpp", (DL_FUNC) &_emdi2_fh_reml_loglik_cpp, 4},
    {"_emdi2_fh_estsigmau2_reml_cpp", (DL_FUNC) &_emdi2_fh_estsigmau2_reml_cpp, 6},
    {"_emdi2_fh_sreml_cpp", (DL_FUNC) &_emdi2_fh_sreml_cpp, 6},
    {"_emdi2_compute_domain_indicators_cpp", (DL_FUNC) &_emdi2_compute_domain_indicators_cpp, 3},
    {"_emdi2_compute_domain_indicators_selective_cpp", (DL_FUNC) &_emdi2_compute_domain_indicators_selective_cpp, 4},
    {"_emdi2_compute_all_indicators_cpp", (DL_FUNC) &_emdi2_compute_all_indicators_cpp, 5},
    {"_emdi2_data_transform_cpp", (DL_FUNC) &_emdi2_data_transform_cpp, 3},
    {"_emdi2_lme_fit_cpp", (DL_FUNC) &_emdi2_lme_fit_cpp, 3},
    {"_emdi2_model_par_weighted_cpp", (DL_FUNC) &_emdi2_model_par_weighted_cpp, 6},
    {"_emdi2_set_omp_threads", (DL_FUNC) &_emdi2_set_omp_threads, 1},
    {"_emdi2_get_omp_threads", (DL_FUNC) &_emdi2_get_omp_threads, 0},
    {"_emdi2_monte_carlo_cpp", (DL_FUNC) &_emdi2_monte_carlo_cpp, 22},
    {"_emdi2_parametric_bootstrap_cpp", (DL_FUNC) &_emdi2_parametric_bootstrap_cpp, 32},
    {"_emdi2_fmt_duration_cpp", (DL_FUNC) &_emdi2_fmt_duration_cpp, 1},
    {"_emdi2_progress_line_cpp", (DL_FUNC) &_emdi2_progress_line_cpp, 5},
    {"_emdi2_progress_header_cpp", (DL_FUNC) &_emdi2_progress_header_cpp, 4},
    {"_emdi2_std_transform_y_cpp", (DL_FUNC) &_emdi2_std_transform_y_cpp, 3},
    {"_emdi2_reml_loglik_cpp", (DL_FUNC) &_emdi2_reml_loglik_cpp, 6},
    {"_emdi2_optimal_parameter_cpp", (DL_FUNC) &_emdi2_optimal_parameter_cpp, 7},
    {"_emdi2_back_transform_cpp", (DL_FUNC) &_emdi2_back_transform_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_emdi2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
