# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_domain_indicators_cpp <- function(y, weights, threshold) {
    .Call(`_emdi2_compute_domain_indicators_cpp`, y, weights, threshold)
}

compute_all_indicators_cpp <- function(y, weights, domain_ids, threshold, n_domains) {
    .Call(`_emdi2_compute_all_indicators_cpp`, y, weights, domain_ids, threshold, n_domains)
}

back_transform_cpp <- function(y, transformation, lambda, shift) {
    .Call(`_emdi2_back_transform_cpp`, y, transformation, lambda, shift)
}

