# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gen_superpop_cpp <- function(mu_fixed, sigmae2, sigmau2, obs_dom, n_pop, N_dom_pop, transformation, lambda, shift) {
    .Call(`_emdi2_gen_superpop_cpp`, mu_fixed, sigmae2, sigmau2, obs_dom, n_pop, N_dom_pop, transformation, lambda, shift)
}

gen_bootstrap_sample_cpp <- function(X_smp, betas, sigmae2, sigmau2, vu_tmp, smp_to_pop_map, n_smp, transformation, lambda, shift) {
    .Call(`_emdi2_gen_bootstrap_sample_cpp`, X_smp, betas, sigmae2, sigmau2, vu_tmp, smp_to_pop_map, n_smp, transformation, lambda, shift)
}

compute_domain_indicators_cpp <- function(y, weights, threshold) {
    .Call(`_emdi2_compute_domain_indicators_cpp`, y, weights, threshold)
}

compute_all_indicators_cpp <- function(y, weights, domain_ids, threshold, n_domains) {
    .Call(`_emdi2_compute_all_indicators_cpp`, y, weights, domain_ids, threshold, n_domains)
}

monte_carlo_cpp <- function(mu, sigmae2, sigmau2, sigmav2, domain_ids, obs_dom, dist_obs_dom, n_pop, N_dom_pop, N_dom_smp, N_dom_unobs, L, threshold, transformation, lambda, shift, pop_weights, n_indicators, agg_domain_ids = NULL, N_dom_agg = 0L) {
    .Call(`_emdi2_monte_carlo_cpp`, mu, sigmae2, sigmau2, sigmav2, domain_ids, obs_dom, dist_obs_dom, n_pop, N_dom_pop, N_dom_smp, N_dom_unobs, L, threshold, transformation, lambda, shift, pop_weights, n_indicators, agg_domain_ids, N_dom_agg)
}

back_transform_cpp <- function(y, transformation, lambda, shift) {
    .Call(`_emdi2_back_transform_cpp`, y, transformation, lambda, shift)
}

